version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data
      - ./mods.txt:/extras/mods.txt:ro
      - ./config:/config
    depends_on:
      - db
    env_file: mc.env 
    environment:

      RCON_PASSWORD: "${RCON_PASSWORD}"
      OPS: ${OPS}

      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # and here are the actual variables
      CFG_DB_HOST: "${DB_HOST}"
      CFG_DB_PORT: "${DB_PORT}"
      CFG_DB_NAME: "${DB_NAME}"
      CFG_DB_USER: "${DB_USER}"
      CFG_DB_ENGINE: "${DB_ENGINE}"
      CFG_DB_PASSWORD_USER: "${DB_USER_PASSWORD}"
      RCON_CMDS_STARTUP: |-
        lp user ${OPS} permission set luckperms.* true
        lp group default setdisplayname Players
        lp group default permission set minecraft.command.say true
        lp group default permission set minecraft.command.me true
        lp creategroup mod
        lp group mod parent add default
        lp group mod setdisplayname Moderators
        lp group mod permission set minecraft.command.mute true
        lp group mod permission set minecraft.command.unmute true
        lp group mod permission set minecraft.command.list true
        lp group mod permission set minecraft.command.whitelist true
        lp group mod permission set minecraft.command.spreadplayers true
        lp creategroup admin
        lp group admin parent add mod
        lp group admin setdisplayname Admins
        lp group admin permission set minecraft.command.ban true
        lp group admin permission set minecraft.command.pardon true
        lp user ShingouzAndCo parent add mod
        lp user Geeecko parent add mod
        lp user Deezys parent add mod

    restart: unless-stopped

  db:
    image: mariadb
    hostname: ${DB_HOST}
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_USER_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  mc-data:
  db-data:
