version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data
      - ./mods.txt:/extras/mods.txt:ro
      - ./config:/config
    depends_on:
      - db
    environment:
      TZ: Europe/Brussels
      EULA: "TRUE"
      TYPE: "PAPER"
      MOTD: "A Luck enbled server"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      RCON_PORT: 28016
      OPS: ${OPS}
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      REMOVE_OLD_MODS: "TRUE"
      MODS_FILE: /extras/mods.txt
      COPY_CONFIG_DEST: /data/plugins/LuckPerms
      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # and here are the actual variables
      CFG_DB_HOST: "${DB_HOST}"
      CFG_DB_PORT: "${DB_PORT}"
      CFG_DB_NAME: "${DB_NAME}"
      CFG_DB_USER: "${DB_USER}"
      CFG_DB_ENGINE: "${DB_ENGINE}"
      CFG_DB_PASSWORD_USER: "${DB_USER_PASSWORD}"
      RCON_CMDS_STARTUP: |-
        lp user ${OPS} permission set luckperms.* true 
        lp creategroup admin
        lp user ${OPS} parent add admin
        lp group admin permission set minecraft.* true
        lp group admin permission set bungeecord.* true
        lp creategroup mod
        lp group mod parent add default
        lp group mod permission set minecraft.command.list true
        lp group mod permission set minecraft.command.say true
        lp group mod permission set minecraft.command.whitelist true
        lp group mod permission set minecraft.command.spreadplayers true
        lp group default permission set bungeecord.command.server true
        lp group default permission set bungeecord.command.list true
        lp group default permission set minecraft.command.give true
        lp group default permission set minecraft.command.help true
        lp group default permission set minecraft.command.me true
        lp group default permission set minecraft.command.msg true

    restart: unless-stopped

  db:
    image: mariadb
    hostname: ${DB_HOST}
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_USER_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  mc-data:
  db-data:
